### ISSUE TITLE
Family

### ISSUE THREAD

**Issue by omikron88** [rejunity/z80-open-silicon#1]
Do you plan to "revive" some other members of Z80 family too, in the future? Such as CTC or PIO?
I can provide some testing of real samples on logic analyser.

How fast the new Z80 will be?

**Comment by rejunity** [comment]
> CTC or PIO

No plans for CTC and PIO yet, mostly because I don't know 8-bit computers that ever used them. If you have a good example / case why they would be important - please let me know!

Instead, I was thinking about packaging Z80 with AY sound processor, Spectrum ULA and maybe TMS99xx, HD6845. Basically making small SoC (System on Chip) that could handle ZX Spectrum, Amstrad CPC and some MSX models. But that is a long term project.

> I can provide some testing of real samples on logic analyser.

That would be great! There are couple of people that volunteered for hardware testing already and I will be looking for several more! I will keep you posted.

> How fast the new Z80 will be?

According to simulation 50 MHz, but maybe 66 MHz.

**Comment by omikron88** [comment]
> No plans for CTC and PIO yet, mostly because I don't know 8-bit computers that ever used them. If you have a good example / case why they would be important - please let me know!

They are, but not so frequently as CPU. Most used is CTC (and also simplest), then PIO. Sharp MZ for example. The rarest is DMA and DART.

> 
> Instead, I was thinking about packaging Z80 with AY sound processor, Spectrum ULA and maybe TMS99xx, HD6845. Basically making small SoC (System on Chip) that could handle ZX Spectrum, Amstrad CPC and some MSX models. But that is a long term project.

This is a good idea. Spectrum ULA is becoming rare. But there is a little problem: Some pins are analog. Video output for example. But ULA is well documented at technology and gate level

**Comment by rejunity** [comment]
> But there is a little problem: Some pins are analog. 

This is not FPGA :) we can do analog pins!
